language: cpp

os: linux
sudo: false

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - bison
            - flex
            - cmake

matrix:
    include:
        - addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-5
          env: SET_COMPILERS="CC=gcc-5 CXX=g++-5"

        - addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty-4.0
                      - ubuntu-toolchain-r-test
                  packages:
                      - clang-3.9
                      - libstdc++-5-dev
          env: SET_COMPILERS="CC=clang CXX=clang++"

env:
    global:
        - GTEST_GIT=https://github.com/google/googletest
        - GTEST_HOME=$HOME/googletest
        - GTEST_BUILD_HOME=$GTEST_HOME/build
        - GTEST_INSTALL_HOME=$GTEST_HOME/install
        - EFD_HOME=$TRAVIS_BUILD_DIR
        - EFD_BUILD_HOME=$EFD_HOME/build
        - EFD_EXE=$EFD_BUILD_HOME/tools/efd

before_install:
    - eval $SET_COMPILERS
    - git clone $GTEST_GIT $GTEST_HOME

install:
    - mkdir -p $GTEST_BUILD_HOME && cd $GTEST_BUILD_HOME
    - cmake -DCMAKE_INSTALL_PREFIX=$GTEST_INSTALL_HOME ../ && make -j4 && make install
    - mkdir -p $EFD_BUILD_HOME && cd $EFD_BUILD_HOME
    - cmake -DGTEST_ROOT=$GTEST_INSTALL_HOME -DENABLE_TESTS=ON ../ && make -j4

script:
    - $EFD_HOME/ci/RunUnitTests.sh
    - $EFD_HOME/ci/RunFunctionalTests.sh
